# Generated by Django 5.1.6 on 2025-03-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedface',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detected_faces/'),
        ),
    ]
